# Generated by Django 3.2.6 on 2021-09-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_income_group', models.IntegerField(choices=[(0, '0- $25K'), (1, '25-$70K'), (2, '>$70K')], default=0)),
                ('customer_region', models.CharField(choices=[('North', 'North'), ('East', 'East'), ('West', 'West'), ('South', 'South')], max_length=200)),
                ('customer_martial_status', models.IntegerField(choices=[(0, 'Single'), (1, 'Married'), (2, 'Other')], default=2)),
                ('customer_gender_status', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=2)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='PolicyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=200)),
                ('date_of_purchase', models.DateField()),
                ('fuel', models.CharField(choices=[('CNG', 'CNG'), ('LNG', 'LNG'), ('LPG', 'LPG')], max_length=200)),
                ('vehicle_segment', models.CharField(choices=[('A', 'Mini Hatchbacks'), ('B', 'Small Hatchbacks'), ('C', 'Small Sedans or family cars'), ('D', 'Mid-Sized Family cars or Sedans'), ('E', 'SExecutive Luxury Cars'), ('F', 'MPVs'), ('G', 'SUVs')], max_length=200)),
                ('premium', models.PositiveIntegerField()),
                ('bodily_injury_liability', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('personal_injury_liability', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('property_damage_liability', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('colision', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('comprehensive', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.customer')),
            ],
            options={
                'db_table': 'policy_details',
            },
        ),
    ]
