# Generated by Django 3.2.6 on 2021-09-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policydetails',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='policydetails',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='policy_details', to='insurance_app.customer'),
        ),
    ]
