# Generated by Django 3.2.6 on 2021-09-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_auto_20210901_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_digit',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
