# Generated by Django 3.2.6 on 2021-09-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0004_auto_20210901_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydetails',
            name='bodily_injury_liability',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policydetails',
            name='colision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policydetails',
            name='comprehensive',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policydetails',
            name='personal_injury_liability',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policydetails',
            name='property_damage_liability',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
