# Generated by Django 3.2.6 on 2021-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_auto_20210903_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydetails',
            name='premium',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
